/* SSP.Q8 — لوحة الشركة */
(() => {
  'use strict';
  const session=window.SSPAuth.requireRole('company','portal.html?role=company'); if(!session)return;
  const $=(id)=>document.getElementById(id), fmt=(n)=>Number(n).toFixed(3);
  const userNameEl=$('userName'),logoutBtn=$('logoutBtn'),subscriptionText=$('subscriptionText'),subscriptionBadge=$('subscriptionBadge'),openRequestList=$('openRequestList'),myQuotesList=$('myQuotesList'),myRequestList=$('myRequestList'),toastContainer=$('toastContainer');
  const quoteModalOverlay=$('quoteModalOverlay'),closeQuoteModalBtn=$('closeQuoteModalBtn'),cancelQuoteModalBtn=$('cancelQuoteModalBtn'),quoteForm=$('quoteForm'),quoteAmountInput=$('quoteAmountInput'),quoteDeliveryInput=$('quoteDeliveryInput'),quoteNoteInput=$('quoteNoteInput');
  let quotingRequestId=null;
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function toast(m){const t=document.createElement('div');t.className='toast';t.textContent=m;toastContainer.appendChild(t);setTimeout(()=>t.remove(),3000);}
  function company(){return window.SSPAuth.getUserByEmail(session.email)||session;}
  function active(){return !!company().subscriptionActive;}
  function name(){return company().companyName||company().name;}
  function renderSubscription(){const a=active();subscriptionText.textContent=a?'نشط':'غير مفعّل';subscriptionBadge.textContent=a?'مفعّل':'غير مفعّل';subscriptionBadge.className='subscription-badge '+(a?'subscription-badge--active':'subscription-badge--inactive');}
  function files(list){return !list||!list.length?'':`<div style="margin-top:10px">${list.map(f=>`<a class="download-chip" download="${esc(f.name)}" href="${f.dataUrl}">تنزيل: ${esc(f.name)}</a>`).join('')}</div>`;}
  function target(r){if(r.targetType==='selected')return 'موجّه لشركات محددة';if(r.targetType==='type')return `موجّه لتخصص: ${esc(r.targetCompanyType)}`;return 'مرسل لجميع الشركات';}
  function renderOpen(){const requests=window.SSPMarketplace.getOpenForCompany(session.email);if(!requests.length){openRequestList.innerHTML='<div class="empty-state">لا توجد حزم مناسبة مفتوحة حالياً.</div>';return;}openRequestList.innerHTML=requests.map(r=>`<article class="request-card"><div class="request-card__main"><h3 class="request-card__title">${esc(r.projectName)}</h3><div class="request-card__meta"><span>${esc(r.tierName)}</span><span>${esc(r.complexityName)}</span><span>${target(r)}</span><span class="mono">${esc(r.sourceReferenceNo||'')}</span></div><p class="request-card__desc">${esc(r.description)}</p>${files(r.attachedFiles)}</div><div class="request-card__side"><span class="status-badge status-badge--open">بانتظار العروض</span>${active()?`<div style="display:flex;gap:8px"><button class="btn btn--outline btn--sm reject-btn" data-id="${r.id}">رفض</button><button class="btn btn--gold btn--sm quote-btn" data-id="${r.id}">تقديم عرض</button></div>`:'<span style="font-size:12.5px">يجب تفعيل الاشتراك قبل تقديم العروض.</span>'}</div></article>`).join('');openRequestList.querySelectorAll('.reject-btn').forEach(b=>b.onclick=()=>{window.SSPMarketplace.dismissForCompany(b.dataset.id,session.email);renderOpen();});openRequestList.querySelectorAll('.quote-btn').forEach(b=>b.onclick=()=>openModal(b.dataset.id));}
  function openModal(id){quotingRequestId=id;quoteForm.reset();quoteModalOverlay.classList.add('is-open');quoteAmountInput.focus();}
  function closeModal(){quotingRequestId=null;quoteModalOverlay.classList.remove('is-open');}
  function submitQuote(e){e.preventDefault();const c=company();const res=window.SSPMarketplace.submitQuote(quotingRequestId,{companyEmail:c.email,companyPhone:c.phone,companyName:c.companyName||c.name,companyType:c.companyType,amount:quoteAmountInput.value,deliveryTime:quoteDeliveryInput.value.trim(),note:quoteNoteInput.value.trim()});if(!res.success)return toast(res.error||'تعذر إرسال العرض');closeModal();renderAll();toast('تم إرسال العرض التقريبي للعميل.');}
  function renderQuotes(){const rows=window.SSPMarketplace.getQuotesByCompany(session.email);if(!rows.length){myQuotesList.innerHTML='<div class="empty-state">لم ترسل عروضاً حتى الآن.</div>';return;}myQuotesList.innerHTML=rows.map(({request:r,quote:q,won})=>{let label='بانتظار رد العميل',cls='status-badge--open';if(r.status==='تم اختيار عرض'){label=won?'اختارك العميل':'اختار العميل شركة أخرى';cls=won?'status-badge--done':'status-badge--progress';}return `<article class="request-card"><div><h3 class="request-card__title">${esc(r.projectName)}</h3><div class="request-card__meta"><span class="mono">عرضك: ${fmt(q.amount)} د.ك</span><span>${esc(q.deliveryTime)}</span></div></div><span class="status-badge ${cls}">${label}</span></article>`;}).join('');}
  function renderSelected(){const rows=window.SSPMarketplace.getSelectedBy(session.email);if(!rows.length){myRequestList.innerHTML='<div class="empty-state">لم يختر أي عميل عرضك حتى الآن.</div>';return;}myRequestList.innerHTML=rows.map(r=>`<article class="request-card"><div class="request-card__main"><h3 class="request-card__title">${esc(r.projectName)}</h3><div class="request-card__meta"><span class="mono">${esc(r.sourceReferenceNo||'')}</span><span>العميل: ${esc(r.ownerEmail)}</span>${r.ownerPhone?`<span>${esc(r.ownerPhone)}</span>`:''}</div><p class="request-card__desc">${esc(r.description)}</p>${files(r.attachedFiles)}<p style="font-size:12.5px;color:var(--color-text-muted);margin-top:10px">تمت الإحالة فقط. الاتفاق والدفع والتنفيذ بين شركتك والعميل مباشرة، ولا يديره SSP.Q8.</p></div><span class="status-badge status-badge--done">تم اختيار عرضك</span></article>`).join('');}
  function renderAll(){renderSubscription();renderOpen();renderQuotes();renderSelected();}
  function init(){userNameEl.textContent=`${name()} — ${company().companyType||''}`;logoutBtn.onclick=()=>{window.SSPAuth.clearSession();location.href='portal.html';};closeQuoteModalBtn.onclick=closeModal;cancelQuoteModalBtn.onclick=closeModal;quoteModalOverlay.onclick=e=>{if(e.target===quoteModalOverlay)closeModal();};quoteForm.addEventListener('submit',submitQuote);renderAll();}
  init();
})();
